export const notes = [
  {
    title: "AI & ML",
    author: "Semester 6",
    coverColor: "#B22222",
    tags: ["AI", "Semester 6"],
    file: "/notes/semester6/AIML.pdf",
  },
  {
    title: "Robotics System Design",
    author: "Semester 7",
    coverColor: "#CD5C5C",
    tags: ["Robotics", "Semester 7"],
    file: "/notes/semester7/RSD.pdf",
  },
  {
    title: "Industrial Robotics Motion Control",
    author: "Semester 7",
    coverColor: "#4682B4",
    tags: ["Robotics", "Semester 7"],
    file: "/notes/semester7/IRMC.pdf",
  },
  {
    title: "Mechatronics System Design",
    author: "Semester 7",
    coverColor: "#006400",
    tags: ["Mechatronics", "Semester 7"],
    file: "/notes/semester7/MSD.pdf",
  },
  {
    title: "Modern Control Systems",
    author: "Semester 6",
    coverColor: "#D9560B",
    tags: ["Control Systems", "Semester 6"],
    file: "/notes/semester6/MCS.pdf",
  },
  {
    title: "Graph Theory and Applications",
    author: "Semester 6",
    coverColor: "#6A5ACD",
    tags: ["Mathematics", "Semester 6"],
    file: "/notes/semester6/GTA.pdf",
  },
  {
    title: "Programmable Logic Controller",
    author: "Semester 6",
    coverColor: "#2F4F4F",
    tags: ["Mechatronics", "Semester 6"],
    file: "/notes/semester6/PLC.pdf",
  },
  {
    title: "Design of Machine Elements",
    author: "Semester 5",
    coverColor: "#8B0000",
    tags: ["Mechatronics", "Semester 5"],
    file: "/notes/semester5/DME.pdf",
  },
  {
    title: "Dynamic System Modelling",
    author: "Semester 5",
    coverColor: "#008B8B",
    tags: ["Control Systems", "Semester 5"],
    file: "/notes/semester5/DSM.pdf",
  },
  {
    title: "Signals and Systems",
    author: "Semester 5",
    coverColor: "#556B2F",
    tags: ["Control Systems", "Semester 5"],
    file: "/notes/semester5/SAS.pdf",
  },
  {
    title: "Rough",
    author: "Semester 5",
    coverColor: "#8B4513",
    tags: ["Miscellaneous", "Semester 5"],
    file: "/notes/semester5/Rough.pdf",
  },
];
